/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsThemeRouteImport } from './routes/settings/theme'
import { Route as SettingsSyncRouteImport } from './routes/settings/sync'
import { Route as SettingsModelsRouteImport } from './routes/settings/models'
import { Route as SettingsGeneralRouteImport } from './routes/settings/general'
import { Route as SettingsEditorRouteImport } from './routes/settings/editor'
import { Route as SettingsDataRouteImport } from './routes/settings/data'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsThemeRoute = SettingsThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSyncRoute = SettingsSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsModelsRoute = SettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsEditorRoute = SettingsEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/about': typeof SettingsAboutRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/editor': typeof SettingsEditorRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/editor': typeof SettingsEditorRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/about': typeof SettingsAboutRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/editor': typeof SettingsEditorRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/settings/about'
    | '/settings/data'
    | '/settings/editor'
    | '/settings/general'
    | '/settings/models'
    | '/settings/sync'
    | '/settings/theme'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/about'
    | '/settings/data'
    | '/settings/editor'
    | '/settings/general'
    | '/settings/models'
    | '/settings/sync'
    | '/settings/theme'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/settings/about'
    | '/settings/data'
    | '/settings/editor'
    | '/settings/general'
    | '/settings/models'
    | '/settings/sync'
    | '/settings/theme'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/theme': {
      id: '/settings/theme'
      path: '/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof SettingsThemeRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/sync': {
      id: '/settings/sync'
      path: '/sync'
      fullPath: '/settings/sync'
      preLoaderRoute: typeof SettingsSyncRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/models': {
      id: '/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof SettingsModelsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/editor': {
      id: '/settings/editor'
      path: '/editor'
      fullPath: '/settings/editor'
      preLoaderRoute: typeof SettingsEditorRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/data': {
      id: '/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsEditorRoute: typeof SettingsEditorRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsModelsRoute: typeof SettingsModelsRoute
  SettingsSyncRoute: typeof SettingsSyncRoute
  SettingsThemeRoute: typeof SettingsThemeRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsDataRoute: SettingsDataRoute,
  SettingsEditorRoute: SettingsEditorRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsModelsRoute: SettingsModelsRoute,
  SettingsSyncRoute: SettingsSyncRoute,
  SettingsThemeRoute: SettingsThemeRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
